version: '3.8'

services:
  rag_system:
    build: . 
    container_name: multimodal_rag_app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./index:/app/index
    env_file:
      - .env 